[en]
  title = "Michael Collins"
  LanguageName = "English"
  weight = 1

[pt]
  title = "Michael Collins" # just for the sake of showing this is possible
  LanguageName = "Português"
  weight = 2

  # tip: assign the default language the lowest Weight